//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : Join_Ctrl.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class Join_Ctrl {
	public void userInformationRegister() {
	}
	
	public void joinCtrl() {
	}
}
