//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : JoinScreen.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class JoinScreen {
	private String name;
	private String tel;
	private String email;
	private String id;
	private String pw;
	private String button;
	public Join_Ctrl joinCtrl_Obj;
	public void joinRequest(String name, String tel, String email, String id, String pw) {
	}
}
