//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : Locker_Ctrl.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class Locker_Ctrl {
	public void lockerUse_Ctrl() {
	}
	
	public void lockerReturn_Ctrl() {
	}
}
