//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : LoginCtrl.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class LoginCtrl {
	private String id;
	private String pw;
	public void loginCtr(String id, String pw) {
	}
}
