//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : LoginScreen.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class LoginScreen {
	private JText id;
	private JText pw;
	private JText join;
	private JText find_id/pw;
	private JText button;
	public LoginCtrl loginCtrl_obj;
	public LoginCtrl Aobj;
	public void loginCtr() {
	}
	
	private void checkverify() {
	}
	
	private void login() {
	}
}
