//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : MoveSeatScreen.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class MoveSeatScreen {
	private String seatLocation;
	private String button;
	public MoveSeat_Ctrl moveSeat_Ctrl_Obj;
	public void moveSeatRequest() {
	}
}
