//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : PurchaseHourPeriodScreen.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class PurchaseHourPeriodScreen {
	private String hour;
	private String period;
	private String button;
	public PurchaseHourPeriod_Ctrl purchaseHourPeriodCtrl_Obj;
	public void purchaseRequest() {
	}
}
