//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : PurchaseHourPeriod_Ctrl.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class PurchaseHourPeriod_Ctrl {
	public void purchase_Ctrl() {
	}
}
