//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : Return_Seat_Ctrl.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class Return_Seat_Ctrl {
	public void returnSeatCtrl() {
	}
}
