//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : UseSeatScreen.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class UseSeatScreen {
	private String seatLocation;
	private String button;
	public UseSeat_Ctrl useSeat_Ctrl_Obj;
	public void useSeatRequest() {
	}
}
