package sw;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : MainScreen.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class MainScreen {
	private String login_Button;
	private String ticket_purchase_Button;
	private String seat_move_Button;
	private String locker_use_Button;
	private String seat_return_Button;
	private String use_seat_Button;
	public void view_screen() {
	}
}
