package sw;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : MoveSeat_Ctrl.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class MoveSeat_Ctrl {
	public void moveSeat_Ctrl() {
	}
}
