package sw;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : Reutrn_Seat_Screen.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class Reutrn_Seat_Screen {
	private String seat_return;
	private String button;
	public Return_Seat_Ctrl returnSeatCtrl_obj;
	public void requestReturnSeat() {
	}
}
