package sw;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : IT독서실예약시스템
//  @ File Name : UseLockerScreen.java
//  @ Date : 2021-12-10
//  @ Author : 
//
//




public class UseLockerScreen {
	private String lockerLocation;
	private String lockerUse;
	private String lockerReturn;
	private String button;
	public Locker_Ctrl Locker_Ctrl_Obj;
	public void LockerUseRequset() {
	}
	
	public void LockerReturnRequset() {
	}
}
